name: Tests

on: [push, pull_request]

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    environment:
        MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check Gas-snapshot
        run: forge snapshot --check

      - name: Run tests
        run: forge test -vvv
          # Change profile to prod. when deploying to production.
          FOUNDRY_PROFILE: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'prod' }}
